In [17]:
import pandas as pd 
import numpy as np 
from sklearn.preprocessing import Binarizer 
names=['preg', 'plas', 'pres', 'skin', 'test', 'mass', 'pedi', 'age', 'class'] 
dataframe=pd.read_csv(r"C:\Users\Amin\Downloads\pima-indians-diabetes.csv", names=names) 
array=dataframe.values

In [18]:
dataframe.head()

,preg,plas,pres,skin,test,mass,pedi,age,class
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1


In [19]:
array

array([[  6.   , 148.   ,  72.   , ...,   0.627,  50.   ,   1.   ],
       [  1.   ,  85.   ,  66.   , ...,   0.351,  31.   ,   0.   ],
       [  8.   , 183.   ,  64.   , ...,   0.672,  32.   ,   1.   ],
       ...,
       [  5.   , 121.   ,  72.   , ...,   0.245,  30.   ,   0.   ],
       [  1.   , 126.   ,  60.   , ...,   0.349,  47.   ,   1.   ],
       [  1.   ,  93.   ,  70.   , ...,   0.315,  23.   ,   0.   ]],
      shape=(768, 9))

In [20]:
#seperate array into input and output components 
#inarize data (set feature values to 0 or 1) according to a threshold 
x=array[:,0:8] 
y=array[:,8] 
x 
binarizer=Binarizer(threshold=7.0).fit(x) 
binaryx=binarizer.transform(x)

In [21]:
binaryx

array([[0., 1., 1., ..., 1., 0., 1.],
       [0., 1., 1., ..., 1., 0., 1.],
       [1., 1., 1., ..., 1., 0., 1.],
       ...,
       [0., 1., 1., ..., 1., 0., 1.],
       [0., 1., 1., ..., 1., 0., 1.],
       [0., 1., 1., ..., 1., 0., 1.]], shape=(768, 8))

In [22]:
#summarize transformed data 
np.set_printoptions(precision=3) 
binaryx[0:5,:] 

array([[0., 1., 1., 1., 0., 1., 0., 1.],
       [0., 1., 1., 1., 0., 1., 0., 1.],
       [1., 1., 1., 0., 0., 1., 0., 1.],
       [0., 1., 1., 1., 1., 1., 0., 1.],
       [0., 1., 1., 1., 1., 1., 0., 1.]])

In [23]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer 
ct= ColumnTransformer([('one_hot_encoder', 
                        OneHotEncoder(categories='auto'), [0])], 
                     remainder='passthrough')

In [24]:
x=ct.fit_transform(x) 
x

array([[ 0.   ,  0.   ,  0.   , ..., 33.6  ,  0.627, 50.   ],
       [ 0.   ,  1.   ,  0.   , ..., 26.6  ,  0.351, 31.   ],
       [ 0.   ,  0.   ,  0.   , ..., 23.3  ,  0.672, 32.   ],
       ...,
       [ 0.   ,  0.   ,  0.   , ..., 26.2  ,  0.245, 30.   ],
       [ 0.   ,  1.   ,  0.   , ..., 30.1  ,  0.349, 47.   ],
       [ 0.   ,  1.   ,  0.   , ..., 30.4  ,  0.315, 23.   ]],
      shape=(768, 24))

In [10]:
#converting categorical data variable into dummy/indicator variables
data = {'gender': ['male', 'female', 'male', 'male'],
        'age': [20, 21, 19, 18],
        'salary': [600, 700, 500, 500]}
data = pd.DataFrame(data)
data

,gender,age,salary
0,male,20,600
1,female,21,700
2,male,19,500
3,male,18,500


In [11]:
pd.get_dummies(data, prefix_sep='_', drop_first=False)

,age,salary,gender_female,gender_male
0,20,600,False,True
1,21,700,True,False
2,19,500,False,True
3,18,500,False,True


In [12]:
pd.get_dummies(data, prefix_sep='_', drop_first=True)

,age,salary,gender_male
0,20,600,True
1,21,700,False
2,19,500,True
3,18,500,True


In [14]:
#StandardScaler
from sklearn.preprocessing import StandardScaler
x=array[:,0:8] 
y=array[:,8] 
scaler=StandardScaler().fit(x) 
rescaledx=scaler.transform(x) 
rescaledx

array([[-0.844, -1.122, -0.16 , ..., -0.684, -0.364, -0.189],
       [ 1.234,  1.944, -0.264, ..., -1.102,  0.605, -0.104],
       [-0.844, -0.997, -0.16 , ..., -0.493, -0.92 , -1.04 ],
       ...,
       [ 0.344,  0.004,  0.15 , ..., -0.734, -0.684, -0.274],
       [-0.844,  0.161, -0.47 , ..., -0.24 , -0.37 ,  1.173],
       [-0.844, -0.872,  0.046, ..., -0.202, -0.473, -0.87 ]],
      shape=(767, 8))

In [15]:
np.set_printoptions(precision=3) 
rescaledx[0:5,:]

array([[-0.844, -1.122, -0.16 ,  0.532, -0.694, -0.684, -0.364, -0.189],
       [ 1.234,  1.944, -0.264, -1.287, -0.694, -1.102,  0.605, -0.104],
       [-0.844, -0.997, -0.16 ,  0.156,  0.122, -0.493, -0.92 , -1.04 ],
       [-1.141,  0.505, -1.504,  0.908,  0.765,  1.409,  5.483, -0.019],
       [ 0.344, -0.152,  0.253, -1.287, -0.694, -0.811, -0.817, -0.274]])

In [16]:
dataframe.head()

,6,148,72,35,0,33.6,0.627,50,1
0,1,85,66,29,0,26.6,0.351,31,0
1,8,183,64,0,0,23.3,0.672,32,1
2,1,89,66,23,94,28.1,0.167,21,0
3,0,137,40,35,168,43.1,2.288,33,1
4,5,116,74,0,0,25.6,0.201,30,0
